# version: '3.8'

services:

  db:
    image: postgres:16-alpine
    restart: always # set shared memory limit when using docker compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - hpc_network


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - hpc_network

volumes:
  postgres_data:

networks:
  hpc_network:
